<a href="https://colab.research.google.com/github/JUSTSUJAY/pytorch_a2z/blob/main/02_gradients.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# PyTorch Fundamentals
## 2. Tensors with Gradients

### Creating Tensor with Gradients
- A Variable wraps a Tensor
- Allows accumulation of gradients

In [1]:
import torch

In [2]:
a = torch.ones((2, 2), requires_grad=True)
a

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [3]:
a.requires_grad

True

In [4]:
# Not a variable
no_gradient = torch.ones(2, 2)

In [5]:
no_gradient.requires_grad

False

In [6]:
# Behaves similarly to tensors
b = torch.ones((2, 2), requires_grad=True)
print(a + b)
print(torch.add(a, b))

tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)
tensor([[2., 2.],
        [2., 2.]], grad_fn=<AddBackward0>)


In [7]:
print(a * b)
print(torch.mul(a, b))

tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)
tensor([[1., 1.],
        [1., 1.]], grad_fn=<MulBackward0>)


### Manually and Automatically Calculating Gradients

**What exactly is `requires_grad`?**
- Allows calculation of gradients w.r.t. the variable

$$y_i = 5(x_i+1)^2$$

In [8]:
x = torch.ones(2, requires_grad=True)
x

tensor([1., 1.], requires_grad=True)

$$y_i\bigr\rvert_{x_i=1} = 5(1 + 1)^2 = 5(2)^2 = 5(4) = 20$$

In [9]:
y = 5 * (x + 1) ** 2
y

tensor([20., 20.], grad_fn=<MulBackward0>)

**Backward should be called only on a scalar (i.e. 1-element tensor) or with gradient w.r.t. the variable** and since our y is a 2-element tensor we need to reduce y to a scalar.

$$o = \frac{1}{2}\sum_i y_i$$

In [11]:
o = (1/2) * torch.sum(y)
o

tensor(20., grad_fn=<MulBackward0>)

<center>
 <strong> y equation:  </strong>   $y_i = 5(x_i+1)^2$
 </center>

<center>
<strong>o equation: </strong>: $o = \frac{1}{2}\sum_i y_i$
</center>

<center>
   <strong>Substitute <code>y</code> in <code>o</code>: </strong> $o = \frac{1}{2} \sum_i 5(x_i+1)^2$
</center>

$$\frac{\partial o}{\partial x_i} = \frac{1}{2}[10(x_i+1)]$$

$$\frac{\partial o}{\partial x_i}\bigr\rvert_{x_i=1} = \frac{1}{2}[10(1 + 1)] = \frac{10}{2}(2) = 10$$

In [12]:
o.backward()

In [13]:
x.grad

tensor([10., 10.])

In [14]:
x.requires_grad

True

In [15]:
y.requires_grad

True

In [16]:
o.requires_grad

True

---
# Summary
- Tensor with Gradients
    - Wraps a tensor for gradient accumulation
- Gradients
    - Define original equation
    - Substitute equation with `x` values
    - Reduce to scalar output, `o` through `mean`
    - Calculate gradients with `o.backward()`
    - Then access gradients of the `x` variable through `x.grad`